apiVersion: v1
kind: ConfigMap
metadata:
  name: viewer-html
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "qgis.labels" . | nindent 4 }}
data:
  index.html: |-
{{ .Files.Get "files/index.html" | indent 4 }}
