apiVersion: v1
kind: ConfigMap
metadata:
  name: project-generator
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "qgis.labels" . | nindent 4 }}
data:
  generate_qgs.py: |-
{{ .Files.Get "files/generate_qgs.py" | indent 4 }}
