apiVersion: v1
kind: Service
metadata:
  name: qgis-server
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "qgis.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "qgis.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: qgis-server
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
